language: rust
sudo: false

matrix:
  include:
    - name: "test (stable)"
      rust: stable
    - name: "test (beta)"
      rust: beta
    - name: "test (nightly)"
      rust: nightly

script:
  - cargo test --all
