[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "fitzgen's art"
documentation = "https://docs.rs/fart"
edition = "2018"
license = "MIT/Apache-2.0"
name = "fart"
readme = "./README.md"
repository = "https://github.com/fitzgen/fart"
version = "0.2.0"

[dependencies]
chrono = "0.4.6"
euclid = "0.19.5"
failure = "0.1.3"
fart-2d-geom = { version = "=0.2.0", path = "crates/2d-geom" }
fart-aabb = { version = "=0.2.0", path = "crates/aabb" }
fart-utils = { version = "=0.2.0", path = "crates/utils" }
id-arena = "2.0.1"
notify = "4.0.6"
num-traits = "0.2.6"
rand = "0.6.1"
structopt = "0.2.14"
svg = "0.5.11"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
quickcheck = "0.8.0"
tempfile = "3.0.5"

[workspace]
