[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
name = "fart"
version = "0.1.0"

[dependencies]
chrono = "0.4.6"
failure = "0.1.3"
notify = "4.0.6"
structopt = "0.2.14"

[dev-dependencies]
assert_cmd = "0.10.2"
predicates = "1.0.0"
tempfile = "3.0.5"
