[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"
name = "fart-aabb"
version = "0.3.0"

[dependencies]
euclid = "0.19.5"
num-traits = "0.2.6"
partial-min-max = { version = "=0.3.0", path = "../partial-min-max" }

[dev-dependencies]
quickcheck = "0.8.2"
