[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "CLI tool for the `fart` framework"
edition = "2018"
license = "MIT/Apache-2.0"
name = "fart-cli"
readme = "../../README.md"
repository = "https://github.com/fitzgen/fart"
version = "0.4.0"

[[bin]]
name = "fart"
path = "src/main.rs"

[dependencies]
async-std = "1.4.0"
chrono = "0.4.10"
failure = "0.1.6"
notify = "4.0.15"
structopt = "0.3.8"
tide = "0.5.1"
futures = "0.3.1"
serde = "1.0.103"
serde_json = "1.0.45"
bytes = "0.5.2"
http-service = "0.4.0"

[dev-dependencies]
assert_cmd = "0.12.0"
predicates = "1.0.2"
quickcheck = "0.9.2"
tempfile = "3.1.0"
